---
title: "Untitled"
author: "Caitie"
date: "2022-08-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(devtools)
#devtools::install_github("JorGarMol/VoCC")
library(VoCC)
#vignette("vocc")

library(ncdf4)
library(raster)

library(gdalUtils)

library(sf)
library(here)
library(tidyverse)
```



```{r}
url<-"https://www.metoffice.gov.uk/hadobs/hadisst/data/HadISST_sst.nc.gz"
destfile<- "/home/kuempel/Clim_Velocity/HadISST_sst.nc.gz"
download.file(url,destfile)
#gunzip(destfile)
unzip_filename <- "/home/kuempel/Clim_Velocity/HadISST_sst.nc"
data <- nc_open(unzip_filename)
```

```{r}
sst_brick<-brick(unzip_filename)
```

```{r}
years<-c(1901:2020)

for(i in 1:length(years)){

sub_x<-subset(x = names(sst_brick), grepl(years[i], names(sst_brick))) 
sub_sst<-subset(sst_brick, sub_x)
sub_sst_mean<-mean(sub_sst, na.rm = T)

writeRaster(sub_sst_mean, paste0("/home/kuempel/Clim_Velocity/SST_",years[[i]],".tif"), overwrite = T)
}

```


# START HERE AFTER INITIAL LOOP

```{r}
sst_files<-list.files("/home/kuempel/Clim_Velocity", pattern = ".tif", full.names = T)
sst_files<-sst_files[!grepl(".aux", sst_files)]

sst<-stack(sst_files)
```

```{r}
tr <- tempTrend(sst, th = 10)
sg <- spatGrad(sst, th = 0.0001, projected = FALSE)
v <- gVoCC(tr, sg)
vel <- v[[1]] # km/yr
ang <- v[[2]] # degrees
```


```{r}
wdpa<-st_read("/home/kuempel/impact_acceleration/data/wdpa/Clean_WDPA_Sept2022.shp")

sub_wdpa<- wdpa %>% 
  filter(PA_DEF != "OECM",
         MARINE == "marine") %>% 
 # mutate(area_km2 = as.numeric(st_area(.))/1e-6) %>% 
  #dplyr::select(WDPAID, NAME, DESIG, PA_DEF, IUCN_CA, STATUS_, ISO3, AREA_KM, MARINE) %>% 
  st_make_valid(.)

sub_wdpa2<-sub_wdpa[!st_is_empty(sub_wdpa),,drop=FALSE]

test<-st_read(here("data/climate_velocity/Check_PAs.shp")) # These are the PAs that are coming up as NAs - some are in the middle of terrestrial area (which is weird.. but whatever) so that makes sense but others seem like they should have values?

#sub_wdpa<- test %>% 
#  filter(PA_DEF != "OECM",
#         MARINE == "marine") %>% 
# # mutate(area_km2 = as.numeric(st_area(.))/1e-6) %>% 
  #dplyr::select(WDPAID, NAME, DESIG, PA_DEF, IUCN_CA, STATUS_, ISO3, AREA_KM, MARINE) %>% 
#  st_make_valid(.)

#sub_wdpa2<-sub_wdpa[!st_is_empty(sub_wdpa),,drop=FALSE]
```

```{r}
#vel_proj<-projectRaster(vel, crs = crs(wdpa))

#writeRaster(vel, here("data/climate_velocity/Velocity.tif"), overwrite = TRUE)

#gdalwarp(srcfile = here("data/climate_velocity/Velocity.tif"), dstfile = here("data/climate_velocity/velocity_proj.tif"), t_srs = "+proj=cea +lat_ts=30 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +type=crs")

#vel_proj<-raster(here("data/climate_velocity/velocity_proj.tif"))
```


```{r}
vel_proj<-raster(here("data/climate_velocity/vel2.tif"))
wdpa_extract<-exactextractr::exact_extract(vel_proj, sub_wdpa2, "mean", progress = T)
```

Climate velocity is km/year

```{r}
wdpa_vocc<-cbind(sub_wdpa2, wdpa_extract) %>% 
  rename(ClimVelocity_km_yr = wdpa_extract)
```

```{r}
wdpa_area<-sub_wdpa2 %>% 
  filter(PA_DEF != "OECM",
         MARINE == "marine") %>% 
  st_transform(., "ESRI:54009") %>% 
  mutate(area_km2 = as.numeric(st_area(.))/1e-6) %>% 
  as.data.frame() %>% 
  dplyr::select(-geometry) %>% 
  dplyr::select(area_km2)

```

```{r}
done<-cbind(wdpa_vocc, wdpa_area)

test<-done %>% 
  dplyr::select(-geometry)
  
test2<-table(test$WDPAID)

```

```{r}
test<-done %>% 
  filter(is.na(ClimVelocity_km_yr) == T)

test2<-done %>% 
  filter(is.na(ClimVelocity_km_yr) == F)

```



```{r}
st_write(done, "/home/kuempel/impact_acceleration/data/climate_velocity/WDPA_marine_climate_velocity.shp", delete_layer = TRUE)
```

# Old code





```{r}
slopedat <- calcslope(sst)
```

```{r}
allyears <- rep(1, nlayers(sst))
mnsst <- stackApply(sst, indices = allyears, fun = mean)
spatx <- spatialgrad(mnsst)
```

```{r}
velodf <- calcvelocity(spatx, slopedat)
```

```{r}
rtrend <- rgrad <- rvocc <- raster(sst)
rgrad[spatx$icell] <- spatx$NS
rtrend[slopedat$icell] <- slopedat$slope
rvocc[velodf$icell] <- velodf$velocity
```
